### ISSUE TITLE
Cloudformation Explode Macro - fails when used with a resource whose property values are of type List

### ISSUE THREAD

**Issue by krn0x2** [awslabs/aws-cloudformation-templates#207]
Using Cloudformation Explode Macro fails when applied to a List property of a resource.

The failure case is mentioned below
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: Explode
Mappings:
  RoleMap:
    Admin:
      Type: AdministratorAccess
    Alexa:
      Type: AlexaForBusinessFullAccess
    ApiGw:
      Type: AmazonAPIGatewayAdministrator
Resources:
  GenericRole:
    ExplodeMap: RoleMap
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/!Explode Type"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
```

Since type of ManagedPolicyArns is a list, using Explode inside its item would fail.
