### ISSUE TITLE
Create S3Object Macro as part of a template

### ISSUE THREAD

**Issue by vennemp** [awslabs/aws-cloudformation-templates#259]
I need a cloudformation template that creates objects in s3 to be used in ec2 user data in the same cloudformation.

The S3object resource looks promising but I would like everything to be created in the same cloudformation.  This will ultimately end up in AWS Marketplace, so I would like the end-user to not have to create something out of band.  

I tried adapting the code using this guys example:
https://binx.io/blog/2018/09/07/using-aws-cloudformation-macros-is-also-plain-and-simple/

But it's failing saying an unsupport property content in the Transform resource.

Do you have an example of this? Honestly, the s3 object seems like a reasonable resource, any idea why this isn't exposed as a public resource for CFN?

Here is my template..
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  TransformFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
              import boto3
              import os

              LAMBDA_ARN = os.environ["LAMBDA_ARN"]

              s3_client = boto3.client("s3")

              def handle_template(request_id, template):
                  new_resources = {}

                  for name, resource in template.get("Resources", {}).items():
                      if resource["Type"] == "AWS::S3::Object":
                          props = resource["Properties"]

                          if len([prop for prop in resource["Properties"] if prop in ["Body", "Base64Body", "Source"]]) != 1:
                              raise Exception("You must specify exactly one of: Body, Base64Body, Source")

                          target = props["Target"]

                          if "ACL" not in target:
                              target["ACL"] = "private"

                          resource_props = {
                              "ServiceToken": LAMBDA_ARN,
                              "Target": target,
                          }

                          if "Body" in props:
                              resource_props["Body"] = props["Body"]

                          elif "Base64Body" in props:
                              resource_props["Base64Body"] = props["Base64Body"]

                          elif "Source" in props:
                              resource_props["Source"] = props["Source"]

                          new_resources[name] = {
                              "Type": "Custom::S3Object",
                              "Version": "1.0",
                              "Properties": resource_props,
                          }

                  for name, resource in new_resources.items():
                      template["Resources"][name] = resource

                  return template

              def handler(event, context):
                  try:
                      template = handle_template(event["requestId"], event["fragment"])
                  except Exception as e:
                      return {
                          "requestId": event["requestId"],
                          "status": "failure",
                          "fragment": event["fragment"],
                      }

                  return {
                      "requestId": event["requestId"],
                      "status": "success",
                      "fragment": template,
                  }
      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt TransformExecutionRole.Arn
  TransformExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
  TransformFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt TransformFunction.Arn
      Principal: "cloudformation.amazonaws.com"
  Transform:
    Type: AWS::CloudFormation::Transform
    Properties:
      Name: !Sub "${AWS::AccountId}::S3Object"
      content: "Generates a text file in S3"
      RoutingTable:
        '*': 0_1
      Versions:
        - VersionName: 0_1
          content: "Version 0_1 of the S3Object Generator"
          FunctionName: !GetAtt TransformFunction.Arn
      ExecutionPolicy:
        Version: 2012-10-17
        Id: AllowOtherAccountPolicy
        Statement:
          - Sid: AllowExecution
            Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action: "cloudformation:CreateChangeSet"
            Resource: !Sub "arn:*:cloudformation:${AWS::Region}:${AWS::AccountId}:transform/S3Object"
```
