### ISSUE TITLE
Unable to use combination of Fn::If and Fn::FindInMap 

### ISSUE THREAD

**Issue by suchitrotti** [awslabs/aws-cloudformation-templates#271]
`DefaultVal: "master"`

```yaml
Mappings:
  EnvironmentBranchName:
    dev:
      BranchName: "development"
```

```yaml
Conditions:
  IsStandardEnvironment:  !Equals [!Ref EnvironmentName, "dev"]
```

```yaml
BranchName: !If [
                    IsStandardEnvironment,
                    !FindInMap [EnvironmentBranchName, !Ref EnvironmentName, "BranchName"],
                    !Ref DefaultVal
                ]
```

> Error:  Fn::FindInMap will always raise an error it if can't find the mapping.
