### ISSUE TITLE
Macro Transform LanguageExtensions not working

### ISSUE THREAD

**Issue by BourgoisMickael** [awslabs/aws-cloudformation-templates#358]
I can't get this code [from the doc][1] to deploy:

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Resources:
  Table:
    Type: AWS::DynamoDB::Table
```

Using `Transform: AWS::LanguageExtensions` always results in

> User: arn:aws:iam::XXX:user/admin is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:us-east-1:aws:transform/LanguageExtensions because no resource-based policy allows the cloudformation:CreateChangeSet action

Note that the user has full access rights.

  [1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/function-refs-in-policy-attributes.html
