### ISSUE TITLE
Deleting a custom resource using the crhelper.py causes cloud formation stack to time out

### ISSUE THREAD

**Issue by reidca** [awslabs/aws-cloudformation-templates#44]
The code in awslabs/aws-cloudformation-templates/blob/master/community/custom_resources/python_custom_resource_helper/crhelper.py it shows that there is no physical id being returned to cloudformation when a custom resource is being deleted. There is just a return event with no arguments.

Therefore I have mirrored this in my code.

```
def delete(event, context):
    """
    Place your code to handle Delete events here
    
    To return a failure to CloudFormation simply raise an exception, the exception message will be sent to CloudFormation Events.
    """
    return
```

 However when I delete the cloudformation stack it timseout deleting the custom resource. 

Looking at the guide here: (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-delete.html) it shows that the PhysicalResourceId should be returned when performing a delete.

Can you please advise whether I am doing something wrong and need to handle the delete event differently for my custom resource.

An example of using the helper with real code would be very useful.

Thanks

**Comment by LRomandine** [comment]
A timeout in CloudFormation means your Lambda function is not sending a response back to CloudFormation to signal success or failure so CloudFormation waits for 30ish minutes and then interprets as a failure.

Some common reasons for Lambda custom resource timeouts include
1. Lambda execution time is longer than the timeout set for the function.
2. Lambda is encountering an error and exiting before sending a failure back to CloudFormation.
3. Lambda code does not send message back to CloudFormation.

Looking at your code, it just returns and crhelper.py should be sending a success message back to CloudFormation.  Have you checked the CloudWatch Logs for your function to troubleshoot the issue?

Tagging @jaymccon since he wrote crhelper.py

**Comment by jaymccon** [comment]
@reidca you are correct that CloudFormation requires a response on delete operations. 

If you are not using the crhelper.py script as per the [example](https://github.com/awslabs/aws-cloudformation-templates/tree/master/community/custom_resources/python_custom_resource_helper) then you will need to explicitly send a response to CloudFormation.

**Comment by reidca** [comment]
Looking at the code (line 123) of the helper:

```
if event['RequestType'] == 'Create':
            physicalResourceId, responseData = create(event, context)
        elif event['RequestType'] == 'Update':
            physicalResourceId, responseData = update(event, context)
        elif event['RequestType'] == 'Delete':
            delete(event, context)
```
The helper function never retrieves the physical id from the client lambda function of the resource that it is deleting so it cannot be send back to cloudformation.

However, the guide (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-delete.html) clearly shows that cloudformation expects a physical resource id and it shoud match the one in the Create or Update methods. Again, from the helper code it seems that in this case physicalResourceId is set to None and it is that which will be returned when cloudformation performs a delete operation.

I am confused whether the helper function is doing the right thing or not and if the client code did want to send back a response to cloudformation whilst using the helper, how would it do this?

Do you have a fleshed out example anywhere that uses the helper function so I can see how this would work? I am new to creating cloudformation custom resources and whilst I am really grateful for this helper class, it would be great to see how it is used in a real example. 

Thanks

**Comment by jaymccon** [comment]
if no PhysicalId is provided to the send function, the CloudWatch logstream name is used:  https://github.com/awslabs/aws-cloudformation-templates/blob/master/community/custom_resources/python_custom_resource_helper/crhelper.py#L60

As far as I'm aware CloudFormation does not use the PhysicalId returned in the response of a Delete event, so there is no issue if it is set to something different than what was received in the request.

As far as an example goes, to build a custom resource that does nothing except return success you can:

1. download the crhelper.py file
2. create a new file called lambda_function.py in the same directory
3. copy the example code from the [README](https://github.com/awslabs/aws-cloudformation-templates/tree/master/community/custom_resources/python_custom_resource_helper) into lambda_function.py 
4. zip both files, ensuring that they are both in the root of the zip file
5. upload the zip file to an s3 bucket
6. create a cloudformation template pointing the "Code" - > "S3Bucket" and "S3Key" properties of the lambda function to the zip in S3
```yaml
Resources:
  ExampleCRRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
           Principal:
             Service: [ "lambda.amazonaws.com" ]
           Action: [ "sts:AssumeRole" ]
      Path: "/"
      ManagedPolicyArns: [ "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole" ]
  ExampleCRLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "lambda_function.handler"
      Role: !GetAtt ExampleCRRole.Arn
      Code:
        ZipFile:
          S3Bucket: <PUT_BUCKET_NAME_HERE>
          S3Key: <PUT_PATH_TO_ZIP_HERE>
      Runtime: "python2.7"
      Timeout: "60"
  ExampleCR:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !GetAtt ExampleCRLambda.Arn
```

If you continue to experience issues please provide some sample code and the CloudWatch logs for the Delete event.
